// Mock of @sigmacomputing/plugin for local dev. HARNESS=1 npm run dev
// SYNTHETIC data only (fabricated ACME Foods / Northgate / Port Vesta) — this file
// is committed to a PUBLIC repo, so it must never contain real shipment data.
const D = {"c_type":["waypoint","loading","travel","temp_out_of_range","temp_back_in_range","alert","unplanned stop","waypoint"],"c_time":[1770000000000,1770136800000,1770144000000,1770432000000,1770453600000,1770540000000,1770720000000,1771080000000],"c_end":[1770144000000,null,1771080000000,null,null,null,1770763200000,null],"c_status":["Shipment origin: Northgate DC","Loaded on vessel at origin port","In transit, leg 1: Northgate DC -> Port Vesta (Meridian Lines)","Temperature out of range (peaked 8.4 C, max 4 C)","Temperature back in range","Light exposure detected","Unplanned stop at Port Calder anchorage","Shipment destination (reached via carrier gate feed): Port Vesta (closest 18 km)"],"c_label":["Waypoint","Loaded","In transit","Temp out of range","Back in range","Alert","Unplanned stop","Waypoint"],"c_eid":[1,2,3,4,5,6,7,8],"c_pid":[null,1,null,3,3,3,3,null],"c_wp":[1,null,null,null,null,null,null,2],"c_mode":["Ocean",null,"Ocean",null,null,null,null,"Road"],"c_leg":[1,1,1,1,1,1,1,2],"c_port":[false,false,false,false,false,false,false,true],"c_dur":[144000,null,936000,null,null,null,43200,null],"c_asrc":["sensor",null,null,null,null,null,null,"container"],"c_dsrc":["sensor",null,null,null,null,null,null,null],"c_icon":["pin","load","transit","thermo-up","thermo-dn","sun","stop","pin"],"c_shape":["pin","circle","bare","triangle","triangle","triangle","octagon","pin"],"c_color":["#2563eb","#16a34a",null,"#dc2626","#0d9488","#dc2626","#d97706","#2563eb"]}
const CONFIG = {"events": "el", "eventType": "c_type", "order": "c_time", "eventEnd": "c_end", "status": "c_status", "label": "c_label", "eventId": "c_eid", "parentId": "c_pid", "waypointNumber": "c_wp", "legMode": "c_mode", "legNumber": "c_leg", "isContainerPort": "c_port", "durationSec": "c_dur", "arrivalSource": "c_asrc", "departureSource": "c_dsrc", "iconKey": "c_icon", "shape": "c_shape", "color": "c_color"}
export const client = { config: { configureEditorPanel(){}, get(){ return CONFIG } } }
export const useConfig = () => CONFIG
export const useElementColumns = () => ({})
export const usePaginatedElementData = () => [D, () => {}]
export const useElementData = () => D
